local tf = (import 'github.com/tf-libsonnet/core/main.libsonnet');
local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='provider', url='', help='`provider` represents the `aws` Terraform provider config.\n\n\n\nThis package contains functions and utilities for setting up the provider using Jsonnet code.\n'),
  '#new':: d.fn(help='\n`aws.provider.new` injects a new `aws` Terraform `provider`\nblock into the root module document.\n\nOptionally, this inserts the provider into the\n[required_providers](https://developer.hashicorp.com/terraform/language/providers/requirements) `terraform` sub block if\nthe `src` and/or `version` parameters are set.\n\n**Args**:\n  - `access_key` (`string`): The access key for API operations. You can retrieve this\nfrom the &#39;Security &amp; Credentials&#39; section of the AWS console. When `null`, the `access_key` field will be omitted from the resulting object.\n  - `allowed_account_ids` (`list`): Set the `allowed_account_ids` field on the resulting provider block. When `null`, the `allowed_account_ids` field will be omitted from the resulting object.\n  - `custom_ca_bundle` (`string`): File containing custom root and intermediate certificates. Can also be configured using the `AWS_CA_BUNDLE` environment variable. (Setting `ca_bundle` in the shared config file is not supported.) When `null`, the `custom_ca_bundle` field will be omitted from the resulting object.\n  - `ec2_metadata_service_endpoint` (`string`): Address of the EC2 metadata service endpoint to use. Can also be configured using the `AWS_EC2_METADATA_SERVICE_ENDPOINT` environment variable. When `null`, the `ec2_metadata_service_endpoint` field will be omitted from the resulting object.\n  - `ec2_metadata_service_endpoint_mode` (`string`): Protocol to use with EC2 metadata service endpoint.Valid values are `IPv4` and `IPv6`. Can also be configured using the `AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE` environment variable. When `null`, the `ec2_metadata_service_endpoint_mode` field will be omitted from the resulting object.\n  - `forbidden_account_ids` (`list`): Set the `forbidden_account_ids` field on the resulting provider block. When `null`, the `forbidden_account_ids` field will be omitted from the resulting object.\n  - `http_proxy` (`string`): The address of an HTTP proxy to use when accessing the AWS API. Can also be configured using the `HTTP_PROXY` or `HTTPS_PROXY` environment variables. When `null`, the `http_proxy` field will be omitted from the resulting object.\n  - `insecure` (`bool`): Explicitly allow the provider to perform &#34;insecure&#34; SSL requests. If omitted, default value is `false` When `null`, the `insecure` field will be omitted from the resulting object.\n  - `max_retries` (`number`): The maximum number of times an AWS API request is\nbeing executed. If the API request still fails, an error is\nthrown. When `null`, the `max_retries` field will be omitted from the resulting object.\n  - `profile` (`string`): The profile for API operations. If not set, the default profile\ncreated with `aws configure` will be used. When `null`, the `profile` field will be omitted from the resulting object.\n  - `region` (`string`): The region where AWS operations will take place. Examples\nare us-east-1, us-west-2, etc. When `null`, the `region` field will be omitted from the resulting object.\n  - `retry_mode` (`string`): Specifies how retries are attempted. Valid values are `standard` and `adaptive`. Can also be configured using the `AWS_RETRY_MODE` environment variable. When `null`, the `retry_mode` field will be omitted from the resulting object.\n  - `s3_use_path_style` (`bool`): Set this to true to enable the request to use path-style addressing,\ni.e., https://s3.amazonaws.com/BUCKET/KEY. By default, the S3 client will\nuse virtual hosted bucket addressing when possible\n(https://BUCKET.s3.amazonaws.com/KEY). Specific to the Amazon S3 service. When `null`, the `s3_use_path_style` field will be omitted from the resulting object.\n  - `secret_key` (`string`): The secret key for API operations. You can retrieve this\nfrom the &#39;Security &amp; Credentials&#39; section of the AWS console. When `null`, the `secret_key` field will be omitted from the resulting object.\n  - `shared_config_files` (`list`): List of paths to shared config files. If not set, defaults to [~/.aws/config]. When `null`, the `shared_config_files` field will be omitted from the resulting object.\n  - `shared_credentials_files` (`list`): List of paths to shared credentials files. If not set, defaults to [~/.aws/credentials]. When `null`, the `shared_credentials_files` field will be omitted from the resulting object.\n  - `skip_credentials_validation` (`bool`): Skip the credentials validation via STS API. Used for AWS API implementations that do not have STS available/implemented. When `null`, the `skip_credentials_validation` field will be omitted from the resulting object.\n  - `skip_metadata_api_check` (`string`): Skip the AWS Metadata API check. Used for AWS API implementations that do not have a metadata api endpoint. When `null`, the `skip_metadata_api_check` field will be omitted from the resulting object.\n  - `skip_region_validation` (`bool`): Skip static validation of region name. Used by users of alternative AWS-like APIs or users w/ access to regions that are not public (yet). When `null`, the `skip_region_validation` field will be omitted from the resulting object.\n  - `skip_requesting_account_id` (`bool`): Skip requesting the account ID. Used for AWS API implementations that do not have IAM/STS API and/or metadata API. When `null`, the `skip_requesting_account_id` field will be omitted from the resulting object.\n  - `sts_region` (`string`): The region where AWS STS operations will take place. Examples\nare us-east-1 and us-west-2. When `null`, the `sts_region` field will be omitted from the resulting object.\n  - `token` (`string`): session token. A session token is only required if you are\nusing temporary security credentials. When `null`, the `token` field will be omitted from the resulting object.\n  - `use_dualstack_endpoint` (`bool`): Resolve an endpoint with DualStack capability When `null`, the `use_dualstack_endpoint` field will be omitted from the resulting object.\n  - `use_fips_endpoint` (`bool`): Resolve an endpoint with FIPS capability When `null`, the `use_fips_endpoint` field will be omitted from the resulting object.\n  - `assume_role` (`list[obj]`): Set the `assume_role` field on the resulting provider block. When `null`, the `assume_role` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.assume_role.new](#fn-awsassumerolenew) constructor.\n  - `assume_role_with_web_identity` (`list[obj]`): Set the `assume_role_with_web_identity` field on the resulting provider block. When `null`, the `assume_role_with_web_identity` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.assume_role_with_web_identity.new](#fn-awsassumerolewithwebidentitynew) constructor.\n  - `default_tags` (`list[obj]`): Configuration block with settings to default resource tags across all resources. When `null`, the `default_tags` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.default_tags.new](#fn-awsdefaulttagsnew) constructor.\n  - `endpoints` (`list[obj]`): Set the `endpoints` field on the resulting provider block. When `null`, the `endpoints` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.endpoints.new](#fn-awsendpointsnew) constructor.\n  - `ignore_tags` (`list[obj]`): Configuration block with settings to ignore resource tags across all resources. When `null`, the `ignore_tags` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.ignore_tags.new](#fn-awsignoretagsnew) constructor.\n  - `alias` (`string`): The provider `alias` to set for this instance of the provider block. When `null`, the `alias`\n  field will be omitted from the resulting provider block.\n  - `src` (`string`): The provider `source` to set on the resulting `required_providers` block. If `src` or `version` is\n  set and is not `null`, a `required_providers` block and entry for the provider will be injected into the document.\n  - `version` (`string`): The provider `version` to set on the resulting `required_providers` block. If `src` or\n  `version` is set and is not `null`, a `required_providers` block and entry for the provider will be injected into the\n  document.\n\n\n**Returns**:\n- A mixin object that injects the new provider (and optionally, `required_providers` block) into the root Terraform configuration.\n', args=[]),
  new(
    access_key=null,
    allowed_account_ids=null,
    assume_role=null,
    assume_role_with_web_identity=null,
    custom_ca_bundle=null,
    default_tags=null,
    ec2_metadata_service_endpoint=null,
    ec2_metadata_service_endpoint_mode=null,
    endpoints=null,
    forbidden_account_ids=null,
    http_proxy=null,
    ignore_tags=null,
    insecure=null,
    max_retries=null,
    profile=null,
    region=null,
    retry_mode=null,
    s3_use_path_style=null,
    secret_key=null,
    shared_config_files=null,
    shared_credentials_files=null,
    skip_credentials_validation=null,
    skip_metadata_api_check=null,
    skip_region_validation=null,
    skip_requesting_account_id=null,
    sts_region=null,
    token=null,
    use_dualstack_endpoint=null,
    use_fips_endpoint=null,
    alias=null,
    src=null,
    version=null
  ):: tf.withProvider(
    name='aws',
    alias=alias,
    src=src,
    version=version,
    attrs=self.newAttrs(
      access_key=access_key,
      allowed_account_ids=allowed_account_ids,
      assume_role=assume_role,
      assume_role_with_web_identity=assume_role_with_web_identity,
      custom_ca_bundle=custom_ca_bundle,
      default_tags=default_tags,
      ec2_metadata_service_endpoint=ec2_metadata_service_endpoint,
      ec2_metadata_service_endpoint_mode=ec2_metadata_service_endpoint_mode,
      endpoints=endpoints,
      forbidden_account_ids=forbidden_account_ids,
      http_proxy=http_proxy,
      ignore_tags=ignore_tags,
      insecure=insecure,
      max_retries=max_retries,
      profile=profile,
      region=region,
      retry_mode=retry_mode,
      s3_use_path_style=s3_use_path_style,
      secret_key=secret_key,
      shared_config_files=shared_config_files,
      shared_credentials_files=shared_credentials_files,
      skip_credentials_validation=skip_credentials_validation,
      skip_metadata_api_check=skip_metadata_api_check,
      skip_region_validation=skip_region_validation,
      skip_requesting_account_id=skip_requesting_account_id,
      sts_region=sts_region,
      token=token,
      use_dualstack_endpoint=use_dualstack_endpoint,
      use_fips_endpoint=use_fips_endpoint
    )
  ),
  '#newAttrs':: d.fn(help='\n`aws.provider.` constructs a new object with attributes and blocks configured for the `aws`\nTerraform `provider`.\n\nUnlike [aws.provider.new](#fn-awsnew), this function will not inject the `provider`\nblock into the root Terraform document. Instead, this must be passed in as the `attrs` argument for the\n[tf.withProvider](https://github.com/tf-libsonnet/core/tree/main/docs#fn-withprovider) function to build a complete block.\n\nThis is most useful when you need to preprocess the attributes with functions, conditional, or looping logic prior to\ninjecting into a complete block.\n\n**Args**:\n  - `access_key` (`string`): The access key for API operations. You can retrieve this\nfrom the &#39;Security &amp; Credentials&#39; section of the AWS console. When `null`, the `access_key` field will be omitted from the resulting object.\n  - `allowed_account_ids` (`list`): Set the `allowed_account_ids` field on the resulting object. When `null`, the `allowed_account_ids` field will be omitted from the resulting object.\n  - `custom_ca_bundle` (`string`): File containing custom root and intermediate certificates. Can also be configured using the `AWS_CA_BUNDLE` environment variable. (Setting `ca_bundle` in the shared config file is not supported.) When `null`, the `custom_ca_bundle` field will be omitted from the resulting object.\n  - `ec2_metadata_service_endpoint` (`string`): Address of the EC2 metadata service endpoint to use. Can also be configured using the `AWS_EC2_METADATA_SERVICE_ENDPOINT` environment variable. When `null`, the `ec2_metadata_service_endpoint` field will be omitted from the resulting object.\n  - `ec2_metadata_service_endpoint_mode` (`string`): Protocol to use with EC2 metadata service endpoint.Valid values are `IPv4` and `IPv6`. Can also be configured using the `AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE` environment variable. When `null`, the `ec2_metadata_service_endpoint_mode` field will be omitted from the resulting object.\n  - `forbidden_account_ids` (`list`): Set the `forbidden_account_ids` field on the resulting object. When `null`, the `forbidden_account_ids` field will be omitted from the resulting object.\n  - `http_proxy` (`string`): The address of an HTTP proxy to use when accessing the AWS API. Can also be configured using the `HTTP_PROXY` or `HTTPS_PROXY` environment variables. When `null`, the `http_proxy` field will be omitted from the resulting object.\n  - `insecure` (`bool`): Explicitly allow the provider to perform &#34;insecure&#34; SSL requests. If omitted, default value is `false` When `null`, the `insecure` field will be omitted from the resulting object.\n  - `max_retries` (`number`): The maximum number of times an AWS API request is\nbeing executed. If the API request still fails, an error is\nthrown. When `null`, the `max_retries` field will be omitted from the resulting object.\n  - `profile` (`string`): The profile for API operations. If not set, the default profile\ncreated with `aws configure` will be used. When `null`, the `profile` field will be omitted from the resulting object.\n  - `region` (`string`): The region where AWS operations will take place. Examples\nare us-east-1, us-west-2, etc. When `null`, the `region` field will be omitted from the resulting object.\n  - `retry_mode` (`string`): Specifies how retries are attempted. Valid values are `standard` and `adaptive`. Can also be configured using the `AWS_RETRY_MODE` environment variable. When `null`, the `retry_mode` field will be omitted from the resulting object.\n  - `s3_use_path_style` (`bool`): Set this to true to enable the request to use path-style addressing,\ni.e., https://s3.amazonaws.com/BUCKET/KEY. By default, the S3 client will\nuse virtual hosted bucket addressing when possible\n(https://BUCKET.s3.amazonaws.com/KEY). Specific to the Amazon S3 service. When `null`, the `s3_use_path_style` field will be omitted from the resulting object.\n  - `secret_key` (`string`): The secret key for API operations. You can retrieve this\nfrom the &#39;Security &amp; Credentials&#39; section of the AWS console. When `null`, the `secret_key` field will be omitted from the resulting object.\n  - `shared_config_files` (`list`): List of paths to shared config files. If not set, defaults to [~/.aws/config]. When `null`, the `shared_config_files` field will be omitted from the resulting object.\n  - `shared_credentials_files` (`list`): List of paths to shared credentials files. If not set, defaults to [~/.aws/credentials]. When `null`, the `shared_credentials_files` field will be omitted from the resulting object.\n  - `skip_credentials_validation` (`bool`): Skip the credentials validation via STS API. Used for AWS API implementations that do not have STS available/implemented. When `null`, the `skip_credentials_validation` field will be omitted from the resulting object.\n  - `skip_metadata_api_check` (`string`): Skip the AWS Metadata API check. Used for AWS API implementations that do not have a metadata api endpoint. When `null`, the `skip_metadata_api_check` field will be omitted from the resulting object.\n  - `skip_region_validation` (`bool`): Skip static validation of region name. Used by users of alternative AWS-like APIs or users w/ access to regions that are not public (yet). When `null`, the `skip_region_validation` field will be omitted from the resulting object.\n  - `skip_requesting_account_id` (`bool`): Skip requesting the account ID. Used for AWS API implementations that do not have IAM/STS API and/or metadata API. When `null`, the `skip_requesting_account_id` field will be omitted from the resulting object.\n  - `sts_region` (`string`): The region where AWS STS operations will take place. Examples\nare us-east-1 and us-west-2. When `null`, the `sts_region` field will be omitted from the resulting object.\n  - `token` (`string`): session token. A session token is only required if you are\nusing temporary security credentials. When `null`, the `token` field will be omitted from the resulting object.\n  - `use_dualstack_endpoint` (`bool`): Resolve an endpoint with DualStack capability When `null`, the `use_dualstack_endpoint` field will be omitted from the resulting object.\n  - `use_fips_endpoint` (`bool`): Resolve an endpoint with FIPS capability When `null`, the `use_fips_endpoint` field will be omitted from the resulting object.\n  - `assume_role` (`list[obj]`): Set the `assume_role` field on the resulting object. When `null`, the `assume_role` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.assume_role.new](#fn-awsassumerolenew) constructor.\n  - `assume_role_with_web_identity` (`list[obj]`): Set the `assume_role_with_web_identity` field on the resulting object. When `null`, the `assume_role_with_web_identity` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.assume_role_with_web_identity.new](#fn-awsassumerolewithwebidentitynew) constructor.\n  - `default_tags` (`list[obj]`): Configuration block with settings to default resource tags across all resources. When `null`, the `default_tags` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.default_tags.new](#fn-awsdefaulttagsnew) constructor.\n  - `endpoints` (`list[obj]`): Set the `endpoints` field on the resulting object. When `null`, the `endpoints` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.endpoints.new](#fn-awsendpointsnew) constructor.\n  - `ignore_tags` (`list[obj]`): Configuration block with settings to ignore resource tags across all resources. When `null`, the `ignore_tags` sub block will be omitted from the resulting object. When setting the sub block, it is recommended to construct the object using the [aws.provider.ignore_tags.new](#fn-awsignoretagsnew) constructor.\n\n**Returns**:\n  - An attribute object that can be used with [tf.withProvider](https://github.com/tf-libsonnet/core/tree/main/docs#fn-withprovider) to construct a new `aws` provider\n  configuration into the root Terraform configuration.\n', args=[]),
  newAttrs(
    access_key=null,
    allowed_account_ids=null,
    assume_role=null,
    assume_role_with_web_identity=null,
    custom_ca_bundle=null,
    default_tags=null,
    ec2_metadata_service_endpoint=null,
    ec2_metadata_service_endpoint_mode=null,
    endpoints=null,
    forbidden_account_ids=null,
    http_proxy=null,
    ignore_tags=null,
    insecure=null,
    max_retries=null,
    profile=null,
    region=null,
    retry_mode=null,
    s3_use_path_style=null,
    secret_key=null,
    shared_config_files=null,
    shared_credentials_files=null,
    skip_credentials_validation=null,
    skip_metadata_api_check=null,
    skip_region_validation=null,
    skip_requesting_account_id=null,
    sts_region=null,
    token=null,
    use_dualstack_endpoint=null,
    use_fips_endpoint=null
  ):: std.prune(a={
    access_key: access_key,
    allowed_account_ids: allowed_account_ids,
    assume_role: assume_role,
    assume_role_with_web_identity: assume_role_with_web_identity,
    custom_ca_bundle: custom_ca_bundle,
    default_tags: default_tags,
    ec2_metadata_service_endpoint: ec2_metadata_service_endpoint,
    ec2_metadata_service_endpoint_mode: ec2_metadata_service_endpoint_mode,
    endpoints: endpoints,
    forbidden_account_ids: forbidden_account_ids,
    http_proxy: http_proxy,
    ignore_tags: ignore_tags,
    insecure: insecure,
    max_retries: max_retries,
    profile: profile,
    region: region,
    retry_mode: retry_mode,
    s3_use_path_style: s3_use_path_style,
    secret_key: secret_key,
    shared_config_files: shared_config_files,
    shared_credentials_files: shared_credentials_files,
    skip_credentials_validation: skip_credentials_validation,
    skip_metadata_api_check: skip_metadata_api_check,
    skip_region_validation: skip_region_validation,
    skip_requesting_account_id: skip_requesting_account_id,
    sts_region: sts_region,
    token: token,
    use_dualstack_endpoint: use_dualstack_endpoint,
    use_fips_endpoint: use_fips_endpoint,
  }),
  assume_role:: {
    '#new':: d.fn(help='\n`aws.assume_role.new` constructs a new object with attributes and blocks configured for the `assume_role`\nTerraform sub block.\n\n\n\n**Args**:\n  - `duration` (`string`): The duration, between 15 minutes and 12 hours, of the role session. Valid time units are ns, us (or µs), ms, s, h, or m. When `null`, the `duration` field will be omitted from the resulting object.\n  - `external_id` (`string`): A unique identifier that might be required when you assume a role in another account. When `null`, the `external_id` field will be omitted from the resulting object.\n  - `policy` (`string`): IAM Policy JSON describing further restricting permissions for the IAM Role being assumed. When `null`, the `policy` field will be omitted from the resulting object.\n  - `policy_arns` (`list`): Amazon Resource Names (ARNs) of IAM Policies describing further restricting permissions for the IAM Role being assumed. When `null`, the `policy_arns` field will be omitted from the resulting object.\n  - `role_arn` (`string`): Amazon Resource Name (ARN) of an IAM Role to assume prior to making API calls. When `null`, the `role_arn` field will be omitted from the resulting object.\n  - `session_name` (`string`): An identifier for the assumed role session. When `null`, the `session_name` field will be omitted from the resulting object.\n  - `source_identity` (`string`): Source identity specified by the principal assuming the role. When `null`, the `source_identity` field will be omitted from the resulting object.\n  - `tags` (`obj`): Assume role session tags. When `null`, the `tags` field will be omitted from the resulting object.\n  - `transitive_tag_keys` (`list`): Assume role session tag keys to pass to any subsequent sessions. When `null`, the `transitive_tag_keys` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `assume_role` sub block.\n', args=[]),
    new(
      duration=null,
      external_id=null,
      policy=null,
      policy_arns=null,
      role_arn=null,
      session_name=null,
      source_identity=null,
      tags=null,
      transitive_tag_keys=null
    ):: std.prune(a={
      duration: duration,
      external_id: external_id,
      policy: policy,
      policy_arns: policy_arns,
      role_arn: role_arn,
      session_name: session_name,
      source_identity: source_identity,
      tags: tags,
      transitive_tag_keys: transitive_tag_keys,
    }),
  },
  assume_role_with_web_identity:: {
    '#new':: d.fn(help='\n`aws.assume_role_with_web_identity.new` constructs a new object with attributes and blocks configured for the `assume_role_with_web_identity`\nTerraform sub block.\n\n\n\n**Args**:\n  - `duration` (`string`): The duration, between 15 minutes and 12 hours, of the role session. Valid time units are ns, us (or µs), ms, s, h, or m. When `null`, the `duration` field will be omitted from the resulting object.\n  - `policy` (`string`): IAM Policy JSON describing further restricting permissions for the IAM Role being assumed. When `null`, the `policy` field will be omitted from the resulting object.\n  - `policy_arns` (`list`): Amazon Resource Names (ARNs) of IAM Policies describing further restricting permissions for the IAM Role being assumed. When `null`, the `policy_arns` field will be omitted from the resulting object.\n  - `role_arn` (`string`): Amazon Resource Name (ARN) of an IAM Role to assume prior to making API calls. When `null`, the `role_arn` field will be omitted from the resulting object.\n  - `session_name` (`string`): An identifier for the assumed role session. When `null`, the `session_name` field will be omitted from the resulting object.\n  - `web_identity_token` (`string`): Set the `web_identity_token` field on the resulting object. When `null`, the `web_identity_token` field will be omitted from the resulting object.\n  - `web_identity_token_file` (`string`): Set the `web_identity_token_file` field on the resulting object. When `null`, the `web_identity_token_file` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `assume_role_with_web_identity` sub block.\n', args=[]),
    new(
      duration=null,
      policy=null,
      policy_arns=null,
      role_arn=null,
      session_name=null,
      web_identity_token=null,
      web_identity_token_file=null
    ):: std.prune(a={
      duration: duration,
      policy: policy,
      policy_arns: policy_arns,
      role_arn: role_arn,
      session_name: session_name,
      web_identity_token: web_identity_token,
      web_identity_token_file: web_identity_token_file,
    }),
  },
  default_tags:: {
    '#new':: d.fn(help='\n`aws.default_tags.new` constructs a new object with attributes and blocks configured for the `default_tags`\nTerraform sub block.\n\n\n\n**Args**:\n  - `tags` (`obj`): Resource tags to default across all resources When `null`, the `tags` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `default_tags` sub block.\n', args=[]),
    new(
      tags=null
    ):: std.prune(a={
      tags: tags,
    }),
  },
  endpoints:: {
    '#new':: d.fn(help='\n`aws.endpoints.new` constructs a new object with attributes and blocks configured for the `endpoints`\nTerraform sub block.\n\n\n\n**Args**:\n  - `accessanalyzer` (`string`): Use this to override the default service endpoint URL When `null`, the `accessanalyzer` field will be omitted from the resulting object.\n  - `account` (`string`): Use this to override the default service endpoint URL When `null`, the `account` field will be omitted from the resulting object.\n  - `acm` (`string`): Use this to override the default service endpoint URL When `null`, the `acm` field will be omitted from the resulting object.\n  - `acmpca` (`string`): Use this to override the default service endpoint URL When `null`, the `acmpca` field will be omitted from the resulting object.\n  - `amg` (`string`): Use this to override the default service endpoint URL When `null`, the `amg` field will be omitted from the resulting object.\n  - `amp` (`string`): Use this to override the default service endpoint URL When `null`, the `amp` field will be omitted from the resulting object.\n  - `amplify` (`string`): Use this to override the default service endpoint URL When `null`, the `amplify` field will be omitted from the resulting object.\n  - `apigateway` (`string`): Use this to override the default service endpoint URL When `null`, the `apigateway` field will be omitted from the resulting object.\n  - `apigatewayv2` (`string`): Use this to override the default service endpoint URL When `null`, the `apigatewayv2` field will be omitted from the resulting object.\n  - `appautoscaling` (`string`): Use this to override the default service endpoint URL When `null`, the `appautoscaling` field will be omitted from the resulting object.\n  - `appconfig` (`string`): Use this to override the default service endpoint URL When `null`, the `appconfig` field will be omitted from the resulting object.\n  - `appflow` (`string`): Use this to override the default service endpoint URL When `null`, the `appflow` field will be omitted from the resulting object.\n  - `appintegrations` (`string`): Use this to override the default service endpoint URL When `null`, the `appintegrations` field will be omitted from the resulting object.\n  - `appintegrationsservice` (`string`): Use this to override the default service endpoint URL When `null`, the `appintegrationsservice` field will be omitted from the resulting object.\n  - `applicationautoscaling` (`string`): Use this to override the default service endpoint URL When `null`, the `applicationautoscaling` field will be omitted from the resulting object.\n  - `applicationinsights` (`string`): Use this to override the default service endpoint URL When `null`, the `applicationinsights` field will be omitted from the resulting object.\n  - `appmesh` (`string`): Use this to override the default service endpoint URL When `null`, the `appmesh` field will be omitted from the resulting object.\n  - `apprunner` (`string`): Use this to override the default service endpoint URL When `null`, the `apprunner` field will be omitted from the resulting object.\n  - `appstream` (`string`): Use this to override the default service endpoint URL When `null`, the `appstream` field will be omitted from the resulting object.\n  - `appsync` (`string`): Use this to override the default service endpoint URL When `null`, the `appsync` field will be omitted from the resulting object.\n  - `athena` (`string`): Use this to override the default service endpoint URL When `null`, the `athena` field will be omitted from the resulting object.\n  - `auditmanager` (`string`): Use this to override the default service endpoint URL When `null`, the `auditmanager` field will be omitted from the resulting object.\n  - `autoscaling` (`string`): Use this to override the default service endpoint URL When `null`, the `autoscaling` field will be omitted from the resulting object.\n  - `autoscalingplans` (`string`): Use this to override the default service endpoint URL When `null`, the `autoscalingplans` field will be omitted from the resulting object.\n  - `backup` (`string`): Use this to override the default service endpoint URL When `null`, the `backup` field will be omitted from the resulting object.\n  - `batch` (`string`): Use this to override the default service endpoint URL When `null`, the `batch` field will be omitted from the resulting object.\n  - `beanstalk` (`string`): Use this to override the default service endpoint URL When `null`, the `beanstalk` field will be omitted from the resulting object.\n  - `budgets` (`string`): Use this to override the default service endpoint URL When `null`, the `budgets` field will be omitted from the resulting object.\n  - `ce` (`string`): Use this to override the default service endpoint URL When `null`, the `ce` field will be omitted from the resulting object.\n  - `chime` (`string`): Use this to override the default service endpoint URL When `null`, the `chime` field will be omitted from the resulting object.\n  - `chimesdkmediapipelines` (`string`): Use this to override the default service endpoint URL When `null`, the `chimesdkmediapipelines` field will be omitted from the resulting object.\n  - `chimesdkvoice` (`string`): Use this to override the default service endpoint URL When `null`, the `chimesdkvoice` field will be omitted from the resulting object.\n  - `cleanrooms` (`string`): Use this to override the default service endpoint URL When `null`, the `cleanrooms` field will be omitted from the resulting object.\n  - `cloud9` (`string`): Use this to override the default service endpoint URL When `null`, the `cloud9` field will be omitted from the resulting object.\n  - `cloudcontrol` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudcontrol` field will be omitted from the resulting object.\n  - `cloudcontrolapi` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudcontrolapi` field will be omitted from the resulting object.\n  - `cloudformation` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudformation` field will be omitted from the resulting object.\n  - `cloudfront` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudfront` field will be omitted from the resulting object.\n  - `cloudhsm` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudhsm` field will be omitted from the resulting object.\n  - `cloudhsmv2` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudhsmv2` field will be omitted from the resulting object.\n  - `cloudsearch` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudsearch` field will be omitted from the resulting object.\n  - `cloudtrail` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudtrail` field will be omitted from the resulting object.\n  - `cloudwatch` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatch` field will be omitted from the resulting object.\n  - `cloudwatchevents` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchevents` field will be omitted from the resulting object.\n  - `cloudwatchevidently` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchevidently` field will be omitted from the resulting object.\n  - `cloudwatchlog` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchlog` field will be omitted from the resulting object.\n  - `cloudwatchlogs` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchlogs` field will be omitted from the resulting object.\n  - `cloudwatchobservabilityaccessmanager` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchobservabilityaccessmanager` field will be omitted from the resulting object.\n  - `cloudwatchrum` (`string`): Use this to override the default service endpoint URL When `null`, the `cloudwatchrum` field will be omitted from the resulting object.\n  - `codeartifact` (`string`): Use this to override the default service endpoint URL When `null`, the `codeartifact` field will be omitted from the resulting object.\n  - `codebuild` (`string`): Use this to override the default service endpoint URL When `null`, the `codebuild` field will be omitted from the resulting object.\n  - `codecatalyst` (`string`): Use this to override the default service endpoint URL When `null`, the `codecatalyst` field will be omitted from the resulting object.\n  - `codecommit` (`string`): Use this to override the default service endpoint URL When `null`, the `codecommit` field will be omitted from the resulting object.\n  - `codedeploy` (`string`): Use this to override the default service endpoint URL When `null`, the `codedeploy` field will be omitted from the resulting object.\n  - `codegurureviewer` (`string`): Use this to override the default service endpoint URL When `null`, the `codegurureviewer` field will be omitted from the resulting object.\n  - `codepipeline` (`string`): Use this to override the default service endpoint URL When `null`, the `codepipeline` field will be omitted from the resulting object.\n  - `codestarconnections` (`string`): Use this to override the default service endpoint URL When `null`, the `codestarconnections` field will be omitted from the resulting object.\n  - `codestarnotifications` (`string`): Use this to override the default service endpoint URL When `null`, the `codestarnotifications` field will be omitted from the resulting object.\n  - `cognitoidentity` (`string`): Use this to override the default service endpoint URL When `null`, the `cognitoidentity` field will be omitted from the resulting object.\n  - `cognitoidentityprovider` (`string`): Use this to override the default service endpoint URL When `null`, the `cognitoidentityprovider` field will be omitted from the resulting object.\n  - `cognitoidp` (`string`): Use this to override the default service endpoint URL When `null`, the `cognitoidp` field will be omitted from the resulting object.\n  - `comprehend` (`string`): Use this to override the default service endpoint URL When `null`, the `comprehend` field will be omitted from the resulting object.\n  - `computeoptimizer` (`string`): Use this to override the default service endpoint URL When `null`, the `computeoptimizer` field will be omitted from the resulting object.\n  - `config` (`string`): Use this to override the default service endpoint URL When `null`, the `config` field will be omitted from the resulting object.\n  - `configservice` (`string`): Use this to override the default service endpoint URL When `null`, the `configservice` field will be omitted from the resulting object.\n  - `connect` (`string`): Use this to override the default service endpoint URL When `null`, the `connect` field will be omitted from the resulting object.\n  - `controltower` (`string`): Use this to override the default service endpoint URL When `null`, the `controltower` field will be omitted from the resulting object.\n  - `costandusagereportservice` (`string`): Use this to override the default service endpoint URL When `null`, the `costandusagereportservice` field will be omitted from the resulting object.\n  - `costexplorer` (`string`): Use this to override the default service endpoint URL When `null`, the `costexplorer` field will be omitted from the resulting object.\n  - `cur` (`string`): Use this to override the default service endpoint URL When `null`, the `cur` field will be omitted from the resulting object.\n  - `databasemigration` (`string`): Use this to override the default service endpoint URL When `null`, the `databasemigration` field will be omitted from the resulting object.\n  - `databasemigrationservice` (`string`): Use this to override the default service endpoint URL When `null`, the `databasemigrationservice` field will be omitted from the resulting object.\n  - `dataexchange` (`string`): Use this to override the default service endpoint URL When `null`, the `dataexchange` field will be omitted from the resulting object.\n  - `datapipeline` (`string`): Use this to override the default service endpoint URL When `null`, the `datapipeline` field will be omitted from the resulting object.\n  - `datasync` (`string`): Use this to override the default service endpoint URL When `null`, the `datasync` field will be omitted from the resulting object.\n  - `dax` (`string`): Use this to override the default service endpoint URL When `null`, the `dax` field will be omitted from the resulting object.\n  - `deploy` (`string`): Use this to override the default service endpoint URL When `null`, the `deploy` field will be omitted from the resulting object.\n  - `detective` (`string`): Use this to override the default service endpoint URL When `null`, the `detective` field will be omitted from the resulting object.\n  - `devicefarm` (`string`): Use this to override the default service endpoint URL When `null`, the `devicefarm` field will be omitted from the resulting object.\n  - `directconnect` (`string`): Use this to override the default service endpoint URL When `null`, the `directconnect` field will be omitted from the resulting object.\n  - `directoryservice` (`string`): Use this to override the default service endpoint URL When `null`, the `directoryservice` field will be omitted from the resulting object.\n  - `dlm` (`string`): Use this to override the default service endpoint URL When `null`, the `dlm` field will be omitted from the resulting object.\n  - `dms` (`string`): Use this to override the default service endpoint URL When `null`, the `dms` field will be omitted from the resulting object.\n  - `docdb` (`string`): Use this to override the default service endpoint URL When `null`, the `docdb` field will be omitted from the resulting object.\n  - `docdbelastic` (`string`): Use this to override the default service endpoint URL When `null`, the `docdbelastic` field will be omitted from the resulting object.\n  - `ds` (`string`): Use this to override the default service endpoint URL When `null`, the `ds` field will be omitted from the resulting object.\n  - `dynamodb` (`string`): Use this to override the default service endpoint URL When `null`, the `dynamodb` field will be omitted from the resulting object.\n  - `ec2` (`string`): Use this to override the default service endpoint URL When `null`, the `ec2` field will be omitted from the resulting object.\n  - `ecr` (`string`): Use this to override the default service endpoint URL When `null`, the `ecr` field will be omitted from the resulting object.\n  - `ecrpublic` (`string`): Use this to override the default service endpoint URL When `null`, the `ecrpublic` field will be omitted from the resulting object.\n  - `ecs` (`string`): Use this to override the default service endpoint URL When `null`, the `ecs` field will be omitted from the resulting object.\n  - `efs` (`string`): Use this to override the default service endpoint URL When `null`, the `efs` field will be omitted from the resulting object.\n  - `eks` (`string`): Use this to override the default service endpoint URL When `null`, the `eks` field will be omitted from the resulting object.\n  - `elasticache` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticache` field will be omitted from the resulting object.\n  - `elasticbeanstalk` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticbeanstalk` field will be omitted from the resulting object.\n  - `elasticloadbalancing` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticloadbalancing` field will be omitted from the resulting object.\n  - `elasticloadbalancingv2` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticloadbalancingv2` field will be omitted from the resulting object.\n  - `elasticsearch` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticsearch` field will be omitted from the resulting object.\n  - `elasticsearchservice` (`string`): Use this to override the default service endpoint URL When `null`, the `elasticsearchservice` field will be omitted from the resulting object.\n  - `elastictranscoder` (`string`): Use this to override the default service endpoint URL When `null`, the `elastictranscoder` field will be omitted from the resulting object.\n  - `elb` (`string`): Use this to override the default service endpoint URL When `null`, the `elb` field will be omitted from the resulting object.\n  - `elbv2` (`string`): Use this to override the default service endpoint URL When `null`, the `elbv2` field will be omitted from the resulting object.\n  - `emr` (`string`): Use this to override the default service endpoint URL When `null`, the `emr` field will be omitted from the resulting object.\n  - `emrcontainers` (`string`): Use this to override the default service endpoint URL When `null`, the `emrcontainers` field will be omitted from the resulting object.\n  - `emrserverless` (`string`): Use this to override the default service endpoint URL When `null`, the `emrserverless` field will be omitted from the resulting object.\n  - `es` (`string`): Use this to override the default service endpoint URL When `null`, the `es` field will be omitted from the resulting object.\n  - `eventbridge` (`string`): Use this to override the default service endpoint URL When `null`, the `eventbridge` field will be omitted from the resulting object.\n  - `events` (`string`): Use this to override the default service endpoint URL When `null`, the `events` field will be omitted from the resulting object.\n  - `evidently` (`string`): Use this to override the default service endpoint URL When `null`, the `evidently` field will be omitted from the resulting object.\n  - `finspace` (`string`): Use this to override the default service endpoint URL When `null`, the `finspace` field will be omitted from the resulting object.\n  - `firehose` (`string`): Use this to override the default service endpoint URL When `null`, the `firehose` field will be omitted from the resulting object.\n  - `fis` (`string`): Use this to override the default service endpoint URL When `null`, the `fis` field will be omitted from the resulting object.\n  - `fms` (`string`): Use this to override the default service endpoint URL When `null`, the `fms` field will be omitted from the resulting object.\n  - `fsx` (`string`): Use this to override the default service endpoint URL When `null`, the `fsx` field will be omitted from the resulting object.\n  - `gamelift` (`string`): Use this to override the default service endpoint URL When `null`, the `gamelift` field will be omitted from the resulting object.\n  - `glacier` (`string`): Use this to override the default service endpoint URL When `null`, the `glacier` field will be omitted from the resulting object.\n  - `globalaccelerator` (`string`): Use this to override the default service endpoint URL When `null`, the `globalaccelerator` field will be omitted from the resulting object.\n  - `glue` (`string`): Use this to override the default service endpoint URL When `null`, the `glue` field will be omitted from the resulting object.\n  - `grafana` (`string`): Use this to override the default service endpoint URL When `null`, the `grafana` field will be omitted from the resulting object.\n  - `greengrass` (`string`): Use this to override the default service endpoint URL When `null`, the `greengrass` field will be omitted from the resulting object.\n  - `guardduty` (`string`): Use this to override the default service endpoint URL When `null`, the `guardduty` field will be omitted from the resulting object.\n  - `healthlake` (`string`): Use this to override the default service endpoint URL When `null`, the `healthlake` field will be omitted from the resulting object.\n  - `iam` (`string`): Use this to override the default service endpoint URL When `null`, the `iam` field will be omitted from the resulting object.\n  - `identitystore` (`string`): Use this to override the default service endpoint URL When `null`, the `identitystore` field will be omitted from the resulting object.\n  - `imagebuilder` (`string`): Use this to override the default service endpoint URL When `null`, the `imagebuilder` field will be omitted from the resulting object.\n  - `inspector` (`string`): Use this to override the default service endpoint URL When `null`, the `inspector` field will be omitted from the resulting object.\n  - `inspector2` (`string`): Use this to override the default service endpoint URL When `null`, the `inspector2` field will be omitted from the resulting object.\n  - `inspectorv2` (`string`): Use this to override the default service endpoint URL When `null`, the `inspectorv2` field will be omitted from the resulting object.\n  - `internetmonitor` (`string`): Use this to override the default service endpoint URL When `null`, the `internetmonitor` field will be omitted from the resulting object.\n  - `iot` (`string`): Use this to override the default service endpoint URL When `null`, the `iot` field will be omitted from the resulting object.\n  - `iotanalytics` (`string`): Use this to override the default service endpoint URL When `null`, the `iotanalytics` field will be omitted from the resulting object.\n  - `iotevents` (`string`): Use this to override the default service endpoint URL When `null`, the `iotevents` field will be omitted from the resulting object.\n  - `ivs` (`string`): Use this to override the default service endpoint URL When `null`, the `ivs` field will be omitted from the resulting object.\n  - `ivschat` (`string`): Use this to override the default service endpoint URL When `null`, the `ivschat` field will be omitted from the resulting object.\n  - `kafka` (`string`): Use this to override the default service endpoint URL When `null`, the `kafka` field will be omitted from the resulting object.\n  - `kafkaconnect` (`string`): Use this to override the default service endpoint URL When `null`, the `kafkaconnect` field will be omitted from the resulting object.\n  - `kendra` (`string`): Use this to override the default service endpoint URL When `null`, the `kendra` field will be omitted from the resulting object.\n  - `keyspaces` (`string`): Use this to override the default service endpoint URL When `null`, the `keyspaces` field will be omitted from the resulting object.\n  - `kinesis` (`string`): Use this to override the default service endpoint URL When `null`, the `kinesis` field will be omitted from the resulting object.\n  - `kinesisanalytics` (`string`): Use this to override the default service endpoint URL When `null`, the `kinesisanalytics` field will be omitted from the resulting object.\n  - `kinesisanalyticsv2` (`string`): Use this to override the default service endpoint URL When `null`, the `kinesisanalyticsv2` field will be omitted from the resulting object.\n  - `kinesisvideo` (`string`): Use this to override the default service endpoint URL When `null`, the `kinesisvideo` field will be omitted from the resulting object.\n  - `kms` (`string`): Use this to override the default service endpoint URL When `null`, the `kms` field will be omitted from the resulting object.\n  - `lakeformation` (`string`): Use this to override the default service endpoint URL When `null`, the `lakeformation` field will be omitted from the resulting object.\n  - `lambda` (`string`): Use this to override the default service endpoint URL When `null`, the `lambda` field will be omitted from the resulting object.\n  - `lex` (`string`): Use this to override the default service endpoint URL When `null`, the `lex` field will be omitted from the resulting object.\n  - `lexmodelbuilding` (`string`): Use this to override the default service endpoint URL When `null`, the `lexmodelbuilding` field will be omitted from the resulting object.\n  - `lexmodelbuildingservice` (`string`): Use this to override the default service endpoint URL When `null`, the `lexmodelbuildingservice` field will be omitted from the resulting object.\n  - `lexmodels` (`string`): Use this to override the default service endpoint URL When `null`, the `lexmodels` field will be omitted from the resulting object.\n  - `licensemanager` (`string`): Use this to override the default service endpoint URL When `null`, the `licensemanager` field will be omitted from the resulting object.\n  - `lightsail` (`string`): Use this to override the default service endpoint URL When `null`, the `lightsail` field will be omitted from the resulting object.\n  - `location` (`string`): Use this to override the default service endpoint URL When `null`, the `location` field will be omitted from the resulting object.\n  - `locationservice` (`string`): Use this to override the default service endpoint URL When `null`, the `locationservice` field will be omitted from the resulting object.\n  - `logs` (`string`): Use this to override the default service endpoint URL When `null`, the `logs` field will be omitted from the resulting object.\n  - `macie2` (`string`): Use this to override the default service endpoint URL When `null`, the `macie2` field will be omitted from the resulting object.\n  - `managedgrafana` (`string`): Use this to override the default service endpoint URL When `null`, the `managedgrafana` field will be omitted from the resulting object.\n  - `mediaconnect` (`string`): Use this to override the default service endpoint URL When `null`, the `mediaconnect` field will be omitted from the resulting object.\n  - `mediaconvert` (`string`): Use this to override the default service endpoint URL When `null`, the `mediaconvert` field will be omitted from the resulting object.\n  - `medialive` (`string`): Use this to override the default service endpoint URL When `null`, the `medialive` field will be omitted from the resulting object.\n  - `mediapackage` (`string`): Use this to override the default service endpoint URL When `null`, the `mediapackage` field will be omitted from the resulting object.\n  - `mediastore` (`string`): Use this to override the default service endpoint URL When `null`, the `mediastore` field will be omitted from the resulting object.\n  - `memorydb` (`string`): Use this to override the default service endpoint URL When `null`, the `memorydb` field will be omitted from the resulting object.\n  - `mq` (`string`): Use this to override the default service endpoint URL When `null`, the `mq` field will be omitted from the resulting object.\n  - `msk` (`string`): Use this to override the default service endpoint URL When `null`, the `msk` field will be omitted from the resulting object.\n  - `mwaa` (`string`): Use this to override the default service endpoint URL When `null`, the `mwaa` field will be omitted from the resulting object.\n  - `neptune` (`string`): Use this to override the default service endpoint URL When `null`, the `neptune` field will be omitted from the resulting object.\n  - `networkfirewall` (`string`): Use this to override the default service endpoint URL When `null`, the `networkfirewall` field will be omitted from the resulting object.\n  - `networkmanager` (`string`): Use this to override the default service endpoint URL When `null`, the `networkmanager` field will be omitted from the resulting object.\n  - `oam` (`string`): Use this to override the default service endpoint URL When `null`, the `oam` field will be omitted from the resulting object.\n  - `opensearch` (`string`): Use this to override the default service endpoint URL When `null`, the `opensearch` field will be omitted from the resulting object.\n  - `opensearchserverless` (`string`): Use this to override the default service endpoint URL When `null`, the `opensearchserverless` field will be omitted from the resulting object.\n  - `opensearchservice` (`string`): Use this to override the default service endpoint URL When `null`, the `opensearchservice` field will be omitted from the resulting object.\n  - `opsworks` (`string`): Use this to override the default service endpoint URL When `null`, the `opsworks` field will be omitted from the resulting object.\n  - `organizations` (`string`): Use this to override the default service endpoint URL When `null`, the `organizations` field will be omitted from the resulting object.\n  - `outposts` (`string`): Use this to override the default service endpoint URL When `null`, the `outposts` field will be omitted from the resulting object.\n  - `pinpoint` (`string`): Use this to override the default service endpoint URL When `null`, the `pinpoint` field will be omitted from the resulting object.\n  - `pipes` (`string`): Use this to override the default service endpoint URL When `null`, the `pipes` field will be omitted from the resulting object.\n  - `pricing` (`string`): Use this to override the default service endpoint URL When `null`, the `pricing` field will be omitted from the resulting object.\n  - `prometheus` (`string`): Use this to override the default service endpoint URL When `null`, the `prometheus` field will be omitted from the resulting object.\n  - `prometheusservice` (`string`): Use this to override the default service endpoint URL When `null`, the `prometheusservice` field will be omitted from the resulting object.\n  - `qldb` (`string`): Use this to override the default service endpoint URL When `null`, the `qldb` field will be omitted from the resulting object.\n  - `quicksight` (`string`): Use this to override the default service endpoint URL When `null`, the `quicksight` field will be omitted from the resulting object.\n  - `ram` (`string`): Use this to override the default service endpoint URL When `null`, the `ram` field will be omitted from the resulting object.\n  - `rbin` (`string`): Use this to override the default service endpoint URL When `null`, the `rbin` field will be omitted from the resulting object.\n  - `rds` (`string`): Use this to override the default service endpoint URL When `null`, the `rds` field will be omitted from the resulting object.\n  - `recyclebin` (`string`): Use this to override the default service endpoint URL When `null`, the `recyclebin` field will be omitted from the resulting object.\n  - `redshift` (`string`): Use this to override the default service endpoint URL When `null`, the `redshift` field will be omitted from the resulting object.\n  - `redshiftdata` (`string`): Use this to override the default service endpoint URL When `null`, the `redshiftdata` field will be omitted from the resulting object.\n  - `redshiftdataapiservice` (`string`): Use this to override the default service endpoint URL When `null`, the `redshiftdataapiservice` field will be omitted from the resulting object.\n  - `redshiftserverless` (`string`): Use this to override the default service endpoint URL When `null`, the `redshiftserverless` field will be omitted from the resulting object.\n  - `resourceexplorer2` (`string`): Use this to override the default service endpoint URL When `null`, the `resourceexplorer2` field will be omitted from the resulting object.\n  - `resourcegroups` (`string`): Use this to override the default service endpoint URL When `null`, the `resourcegroups` field will be omitted from the resulting object.\n  - `resourcegroupstagging` (`string`): Use this to override the default service endpoint URL When `null`, the `resourcegroupstagging` field will be omitted from the resulting object.\n  - `resourcegroupstaggingapi` (`string`): Use this to override the default service endpoint URL When `null`, the `resourcegroupstaggingapi` field will be omitted from the resulting object.\n  - `rolesanywhere` (`string`): Use this to override the default service endpoint URL When `null`, the `rolesanywhere` field will be omitted from the resulting object.\n  - `route53` (`string`): Use this to override the default service endpoint URL When `null`, the `route53` field will be omitted from the resulting object.\n  - `route53domains` (`string`): Use this to override the default service endpoint URL When `null`, the `route53domains` field will be omitted from the resulting object.\n  - `route53recoverycontrolconfig` (`string`): Use this to override the default service endpoint URL When `null`, the `route53recoverycontrolconfig` field will be omitted from the resulting object.\n  - `route53recoveryreadiness` (`string`): Use this to override the default service endpoint URL When `null`, the `route53recoveryreadiness` field will be omitted from the resulting object.\n  - `route53resolver` (`string`): Use this to override the default service endpoint URL When `null`, the `route53resolver` field will be omitted from the resulting object.\n  - `rum` (`string`): Use this to override the default service endpoint URL When `null`, the `rum` field will be omitted from the resulting object.\n  - `s3` (`string`): Use this to override the default service endpoint URL When `null`, the `s3` field will be omitted from the resulting object.\n  - `s3api` (`string`): Use this to override the default service endpoint URL When `null`, the `s3api` field will be omitted from the resulting object.\n  - `s3control` (`string`): Use this to override the default service endpoint URL When `null`, the `s3control` field will be omitted from the resulting object.\n  - `s3outposts` (`string`): Use this to override the default service endpoint URL When `null`, the `s3outposts` field will be omitted from the resulting object.\n  - `sagemaker` (`string`): Use this to override the default service endpoint URL When `null`, the `sagemaker` field will be omitted from the resulting object.\n  - `scheduler` (`string`): Use this to override the default service endpoint URL When `null`, the `scheduler` field will be omitted from the resulting object.\n  - `schemas` (`string`): Use this to override the default service endpoint URL When `null`, the `schemas` field will be omitted from the resulting object.\n  - `sdb` (`string`): Use this to override the default service endpoint URL When `null`, the `sdb` field will be omitted from the resulting object.\n  - `secretsmanager` (`string`): Use this to override the default service endpoint URL When `null`, the `secretsmanager` field will be omitted from the resulting object.\n  - `securityhub` (`string`): Use this to override the default service endpoint URL When `null`, the `securityhub` field will be omitted from the resulting object.\n  - `securitylake` (`string`): Use this to override the default service endpoint URL When `null`, the `securitylake` field will be omitted from the resulting object.\n  - `serverlessapplicationrepository` (`string`): Use this to override the default service endpoint URL When `null`, the `serverlessapplicationrepository` field will be omitted from the resulting object.\n  - `serverlessapprepo` (`string`): Use this to override the default service endpoint URL When `null`, the `serverlessapprepo` field will be omitted from the resulting object.\n  - `serverlessrepo` (`string`): Use this to override the default service endpoint URL When `null`, the `serverlessrepo` field will be omitted from the resulting object.\n  - `servicecatalog` (`string`): Use this to override the default service endpoint URL When `null`, the `servicecatalog` field will be omitted from the resulting object.\n  - `servicediscovery` (`string`): Use this to override the default service endpoint URL When `null`, the `servicediscovery` field will be omitted from the resulting object.\n  - `servicequotas` (`string`): Use this to override the default service endpoint URL When `null`, the `servicequotas` field will be omitted from the resulting object.\n  - `ses` (`string`): Use this to override the default service endpoint URL When `null`, the `ses` field will be omitted from the resulting object.\n  - `sesv2` (`string`): Use this to override the default service endpoint URL When `null`, the `sesv2` field will be omitted from the resulting object.\n  - `sfn` (`string`): Use this to override the default service endpoint URL When `null`, the `sfn` field will be omitted from the resulting object.\n  - `shield` (`string`): Use this to override the default service endpoint URL When `null`, the `shield` field will be omitted from the resulting object.\n  - `signer` (`string`): Use this to override the default service endpoint URL When `null`, the `signer` field will be omitted from the resulting object.\n  - `simpledb` (`string`): Use this to override the default service endpoint URL When `null`, the `simpledb` field will be omitted from the resulting object.\n  - `sns` (`string`): Use this to override the default service endpoint URL When `null`, the `sns` field will be omitted from the resulting object.\n  - `sqs` (`string`): Use this to override the default service endpoint URL When `null`, the `sqs` field will be omitted from the resulting object.\n  - `ssm` (`string`): Use this to override the default service endpoint URL When `null`, the `ssm` field will be omitted from the resulting object.\n  - `ssmcontacts` (`string`): Use this to override the default service endpoint URL When `null`, the `ssmcontacts` field will be omitted from the resulting object.\n  - `ssmincidents` (`string`): Use this to override the default service endpoint URL When `null`, the `ssmincidents` field will be omitted from the resulting object.\n  - `ssoadmin` (`string`): Use this to override the default service endpoint URL When `null`, the `ssoadmin` field will be omitted from the resulting object.\n  - `stepfunctions` (`string`): Use this to override the default service endpoint URL When `null`, the `stepfunctions` field will be omitted from the resulting object.\n  - `storagegateway` (`string`): Use this to override the default service endpoint URL When `null`, the `storagegateway` field will be omitted from the resulting object.\n  - `sts` (`string`): Use this to override the default service endpoint URL When `null`, the `sts` field will be omitted from the resulting object.\n  - `swf` (`string`): Use this to override the default service endpoint URL When `null`, the `swf` field will be omitted from the resulting object.\n  - `synthetics` (`string`): Use this to override the default service endpoint URL When `null`, the `synthetics` field will be omitted from the resulting object.\n  - `timestreamwrite` (`string`): Use this to override the default service endpoint URL When `null`, the `timestreamwrite` field will be omitted from the resulting object.\n  - `transcribe` (`string`): Use this to override the default service endpoint URL When `null`, the `transcribe` field will be omitted from the resulting object.\n  - `transcribeservice` (`string`): Use this to override the default service endpoint URL When `null`, the `transcribeservice` field will be omitted from the resulting object.\n  - `transfer` (`string`): Use this to override the default service endpoint URL When `null`, the `transfer` field will be omitted from the resulting object.\n  - `verifiedpermissions` (`string`): Use this to override the default service endpoint URL When `null`, the `verifiedpermissions` field will be omitted from the resulting object.\n  - `vpclattice` (`string`): Use this to override the default service endpoint URL When `null`, the `vpclattice` field will be omitted from the resulting object.\n  - `waf` (`string`): Use this to override the default service endpoint URL When `null`, the `waf` field will be omitted from the resulting object.\n  - `wafregional` (`string`): Use this to override the default service endpoint URL When `null`, the `wafregional` field will be omitted from the resulting object.\n  - `wafv2` (`string`): Use this to override the default service endpoint URL When `null`, the `wafv2` field will be omitted from the resulting object.\n  - `worklink` (`string`): Use this to override the default service endpoint URL When `null`, the `worklink` field will be omitted from the resulting object.\n  - `workspaces` (`string`): Use this to override the default service endpoint URL When `null`, the `workspaces` field will be omitted from the resulting object.\n  - `xray` (`string`): Use this to override the default service endpoint URL When `null`, the `xray` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `endpoints` sub block.\n', args=[]),
    new(
      accessanalyzer=null,
      account=null,
      acm=null,
      acmpca=null,
      amg=null,
      amp=null,
      amplify=null,
      apigateway=null,
      apigatewayv2=null,
      appautoscaling=null,
      appconfig=null,
      appflow=null,
      appintegrations=null,
      appintegrationsservice=null,
      applicationautoscaling=null,
      applicationinsights=null,
      appmesh=null,
      apprunner=null,
      appstream=null,
      appsync=null,
      athena=null,
      auditmanager=null,
      autoscaling=null,
      autoscalingplans=null,
      backup=null,
      batch=null,
      beanstalk=null,
      budgets=null,
      ce=null,
      chime=null,
      chimesdkmediapipelines=null,
      chimesdkvoice=null,
      cleanrooms=null,
      cloud9=null,
      cloudcontrol=null,
      cloudcontrolapi=null,
      cloudformation=null,
      cloudfront=null,
      cloudhsm=null,
      cloudhsmv2=null,
      cloudsearch=null,
      cloudtrail=null,
      cloudwatch=null,
      cloudwatchevents=null,
      cloudwatchevidently=null,
      cloudwatchlog=null,
      cloudwatchlogs=null,
      cloudwatchobservabilityaccessmanager=null,
      cloudwatchrum=null,
      codeartifact=null,
      codebuild=null,
      codecatalyst=null,
      codecommit=null,
      codedeploy=null,
      codegurureviewer=null,
      codepipeline=null,
      codestarconnections=null,
      codestarnotifications=null,
      cognitoidentity=null,
      cognitoidentityprovider=null,
      cognitoidp=null,
      comprehend=null,
      computeoptimizer=null,
      config=null,
      configservice=null,
      connect=null,
      controltower=null,
      costandusagereportservice=null,
      costexplorer=null,
      cur=null,
      databasemigration=null,
      databasemigrationservice=null,
      dataexchange=null,
      datapipeline=null,
      datasync=null,
      dax=null,
      deploy=null,
      detective=null,
      devicefarm=null,
      directconnect=null,
      directoryservice=null,
      dlm=null,
      dms=null,
      docdb=null,
      docdbelastic=null,
      ds=null,
      dynamodb=null,
      ec2=null,
      ecr=null,
      ecrpublic=null,
      ecs=null,
      efs=null,
      eks=null,
      elasticache=null,
      elasticbeanstalk=null,
      elasticloadbalancing=null,
      elasticloadbalancingv2=null,
      elasticsearch=null,
      elasticsearchservice=null,
      elastictranscoder=null,
      elb=null,
      elbv2=null,
      emr=null,
      emrcontainers=null,
      emrserverless=null,
      es=null,
      eventbridge=null,
      events=null,
      evidently=null,
      finspace=null,
      firehose=null,
      fis=null,
      fms=null,
      fsx=null,
      gamelift=null,
      glacier=null,
      globalaccelerator=null,
      glue=null,
      grafana=null,
      greengrass=null,
      guardduty=null,
      healthlake=null,
      iam=null,
      identitystore=null,
      imagebuilder=null,
      inspector=null,
      inspector2=null,
      inspectorv2=null,
      internetmonitor=null,
      iot=null,
      iotanalytics=null,
      iotevents=null,
      ivs=null,
      ivschat=null,
      kafka=null,
      kafkaconnect=null,
      kendra=null,
      keyspaces=null,
      kinesis=null,
      kinesisanalytics=null,
      kinesisanalyticsv2=null,
      kinesisvideo=null,
      kms=null,
      lakeformation=null,
      lambda=null,
      lex=null,
      lexmodelbuilding=null,
      lexmodelbuildingservice=null,
      lexmodels=null,
      licensemanager=null,
      lightsail=null,
      location=null,
      locationservice=null,
      logs=null,
      macie2=null,
      managedgrafana=null,
      mediaconnect=null,
      mediaconvert=null,
      medialive=null,
      mediapackage=null,
      mediastore=null,
      memorydb=null,
      mq=null,
      msk=null,
      mwaa=null,
      neptune=null,
      networkfirewall=null,
      networkmanager=null,
      oam=null,
      opensearch=null,
      opensearchserverless=null,
      opensearchservice=null,
      opsworks=null,
      organizations=null,
      outposts=null,
      pinpoint=null,
      pipes=null,
      pricing=null,
      prometheus=null,
      prometheusservice=null,
      qldb=null,
      quicksight=null,
      ram=null,
      rbin=null,
      rds=null,
      recyclebin=null,
      redshift=null,
      redshiftdata=null,
      redshiftdataapiservice=null,
      redshiftserverless=null,
      resourceexplorer2=null,
      resourcegroups=null,
      resourcegroupstagging=null,
      resourcegroupstaggingapi=null,
      rolesanywhere=null,
      route53=null,
      route53domains=null,
      route53recoverycontrolconfig=null,
      route53recoveryreadiness=null,
      route53resolver=null,
      rum=null,
      s3=null,
      s3api=null,
      s3control=null,
      s3outposts=null,
      sagemaker=null,
      scheduler=null,
      schemas=null,
      sdb=null,
      secretsmanager=null,
      securityhub=null,
      securitylake=null,
      serverlessapplicationrepository=null,
      serverlessapprepo=null,
      serverlessrepo=null,
      servicecatalog=null,
      servicediscovery=null,
      servicequotas=null,
      ses=null,
      sesv2=null,
      sfn=null,
      shield=null,
      signer=null,
      simpledb=null,
      sns=null,
      sqs=null,
      ssm=null,
      ssmcontacts=null,
      ssmincidents=null,
      ssoadmin=null,
      stepfunctions=null,
      storagegateway=null,
      sts=null,
      swf=null,
      synthetics=null,
      timestreamwrite=null,
      transcribe=null,
      transcribeservice=null,
      transfer=null,
      verifiedpermissions=null,
      vpclattice=null,
      waf=null,
      wafregional=null,
      wafv2=null,
      worklink=null,
      workspaces=null,
      xray=null
    ):: std.prune(a={
      accessanalyzer: accessanalyzer,
      account: account,
      acm: acm,
      acmpca: acmpca,
      amg: amg,
      amp: amp,
      amplify: amplify,
      apigateway: apigateway,
      apigatewayv2: apigatewayv2,
      appautoscaling: appautoscaling,
      appconfig: appconfig,
      appflow: appflow,
      appintegrations: appintegrations,
      appintegrationsservice: appintegrationsservice,
      applicationautoscaling: applicationautoscaling,
      applicationinsights: applicationinsights,
      appmesh: appmesh,
      apprunner: apprunner,
      appstream: appstream,
      appsync: appsync,
      athena: athena,
      auditmanager: auditmanager,
      autoscaling: autoscaling,
      autoscalingplans: autoscalingplans,
      backup: backup,
      batch: batch,
      beanstalk: beanstalk,
      budgets: budgets,
      ce: ce,
      chime: chime,
      chimesdkmediapipelines: chimesdkmediapipelines,
      chimesdkvoice: chimesdkvoice,
      cleanrooms: cleanrooms,
      cloud9: cloud9,
      cloudcontrol: cloudcontrol,
      cloudcontrolapi: cloudcontrolapi,
      cloudformation: cloudformation,
      cloudfront: cloudfront,
      cloudhsm: cloudhsm,
      cloudhsmv2: cloudhsmv2,
      cloudsearch: cloudsearch,
      cloudtrail: cloudtrail,
      cloudwatch: cloudwatch,
      cloudwatchevents: cloudwatchevents,
      cloudwatchevidently: cloudwatchevidently,
      cloudwatchlog: cloudwatchlog,
      cloudwatchlogs: cloudwatchlogs,
      cloudwatchobservabilityaccessmanager: cloudwatchobservabilityaccessmanager,
      cloudwatchrum: cloudwatchrum,
      codeartifact: codeartifact,
      codebuild: codebuild,
      codecatalyst: codecatalyst,
      codecommit: codecommit,
      codedeploy: codedeploy,
      codegurureviewer: codegurureviewer,
      codepipeline: codepipeline,
      codestarconnections: codestarconnections,
      codestarnotifications: codestarnotifications,
      cognitoidentity: cognitoidentity,
      cognitoidentityprovider: cognitoidentityprovider,
      cognitoidp: cognitoidp,
      comprehend: comprehend,
      computeoptimizer: computeoptimizer,
      config: config,
      configservice: configservice,
      connect: connect,
      controltower: controltower,
      costandusagereportservice: costandusagereportservice,
      costexplorer: costexplorer,
      cur: cur,
      databasemigration: databasemigration,
      databasemigrationservice: databasemigrationservice,
      dataexchange: dataexchange,
      datapipeline: datapipeline,
      datasync: datasync,
      dax: dax,
      deploy: deploy,
      detective: detective,
      devicefarm: devicefarm,
      directconnect: directconnect,
      directoryservice: directoryservice,
      dlm: dlm,
      dms: dms,
      docdb: docdb,
      docdbelastic: docdbelastic,
      ds: ds,
      dynamodb: dynamodb,
      ec2: ec2,
      ecr: ecr,
      ecrpublic: ecrpublic,
      ecs: ecs,
      efs: efs,
      eks: eks,
      elasticache: elasticache,
      elasticbeanstalk: elasticbeanstalk,
      elasticloadbalancing: elasticloadbalancing,
      elasticloadbalancingv2: elasticloadbalancingv2,
      elasticsearch: elasticsearch,
      elasticsearchservice: elasticsearchservice,
      elastictranscoder: elastictranscoder,
      elb: elb,
      elbv2: elbv2,
      emr: emr,
      emrcontainers: emrcontainers,
      emrserverless: emrserverless,
      es: es,
      eventbridge: eventbridge,
      events: events,
      evidently: evidently,
      finspace: finspace,
      firehose: firehose,
      fis: fis,
      fms: fms,
      fsx: fsx,
      gamelift: gamelift,
      glacier: glacier,
      globalaccelerator: globalaccelerator,
      glue: glue,
      grafana: grafana,
      greengrass: greengrass,
      guardduty: guardduty,
      healthlake: healthlake,
      iam: iam,
      identitystore: identitystore,
      imagebuilder: imagebuilder,
      inspector: inspector,
      inspector2: inspector2,
      inspectorv2: inspectorv2,
      internetmonitor: internetmonitor,
      iot: iot,
      iotanalytics: iotanalytics,
      iotevents: iotevents,
      ivs: ivs,
      ivschat: ivschat,
      kafka: kafka,
      kafkaconnect: kafkaconnect,
      kendra: kendra,
      keyspaces: keyspaces,
      kinesis: kinesis,
      kinesisanalytics: kinesisanalytics,
      kinesisanalyticsv2: kinesisanalyticsv2,
      kinesisvideo: kinesisvideo,
      kms: kms,
      lakeformation: lakeformation,
      lambda: lambda,
      lex: lex,
      lexmodelbuilding: lexmodelbuilding,
      lexmodelbuildingservice: lexmodelbuildingservice,
      lexmodels: lexmodels,
      licensemanager: licensemanager,
      lightsail: lightsail,
      location: location,
      locationservice: locationservice,
      logs: logs,
      macie2: macie2,
      managedgrafana: managedgrafana,
      mediaconnect: mediaconnect,
      mediaconvert: mediaconvert,
      medialive: medialive,
      mediapackage: mediapackage,
      mediastore: mediastore,
      memorydb: memorydb,
      mq: mq,
      msk: msk,
      mwaa: mwaa,
      neptune: neptune,
      networkfirewall: networkfirewall,
      networkmanager: networkmanager,
      oam: oam,
      opensearch: opensearch,
      opensearchserverless: opensearchserverless,
      opensearchservice: opensearchservice,
      opsworks: opsworks,
      organizations: organizations,
      outposts: outposts,
      pinpoint: pinpoint,
      pipes: pipes,
      pricing: pricing,
      prometheus: prometheus,
      prometheusservice: prometheusservice,
      qldb: qldb,
      quicksight: quicksight,
      ram: ram,
      rbin: rbin,
      rds: rds,
      recyclebin: recyclebin,
      redshift: redshift,
      redshiftdata: redshiftdata,
      redshiftdataapiservice: redshiftdataapiservice,
      redshiftserverless: redshiftserverless,
      resourceexplorer2: resourceexplorer2,
      resourcegroups: resourcegroups,
      resourcegroupstagging: resourcegroupstagging,
      resourcegroupstaggingapi: resourcegroupstaggingapi,
      rolesanywhere: rolesanywhere,
      route53: route53,
      route53domains: route53domains,
      route53recoverycontrolconfig: route53recoverycontrolconfig,
      route53recoveryreadiness: route53recoveryreadiness,
      route53resolver: route53resolver,
      rum: rum,
      s3: s3,
      s3api: s3api,
      s3control: s3control,
      s3outposts: s3outposts,
      sagemaker: sagemaker,
      scheduler: scheduler,
      schemas: schemas,
      sdb: sdb,
      secretsmanager: secretsmanager,
      securityhub: securityhub,
      securitylake: securitylake,
      serverlessapplicationrepository: serverlessapplicationrepository,
      serverlessapprepo: serverlessapprepo,
      serverlessrepo: serverlessrepo,
      servicecatalog: servicecatalog,
      servicediscovery: servicediscovery,
      servicequotas: servicequotas,
      ses: ses,
      sesv2: sesv2,
      sfn: sfn,
      shield: shield,
      signer: signer,
      simpledb: simpledb,
      sns: sns,
      sqs: sqs,
      ssm: ssm,
      ssmcontacts: ssmcontacts,
      ssmincidents: ssmincidents,
      ssoadmin: ssoadmin,
      stepfunctions: stepfunctions,
      storagegateway: storagegateway,
      sts: sts,
      swf: swf,
      synthetics: synthetics,
      timestreamwrite: timestreamwrite,
      transcribe: transcribe,
      transcribeservice: transcribeservice,
      transfer: transfer,
      verifiedpermissions: verifiedpermissions,
      vpclattice: vpclattice,
      waf: waf,
      wafregional: wafregional,
      wafv2: wafv2,
      worklink: worklink,
      workspaces: workspaces,
      xray: xray,
    }),
  },
  ignore_tags:: {
    '#new':: d.fn(help='\n`aws.ignore_tags.new` constructs a new object with attributes and blocks configured for the `ignore_tags`\nTerraform sub block.\n\n\n\n**Args**:\n  - `key_prefixes` (`list`): Resource tag key prefixes to ignore across all resources. When `null`, the `key_prefixes` field will be omitted from the resulting object.\n  - `keys` (`list`): Resource tag keys to ignore across all resources. When `null`, the `keys` field will be omitted from the resulting object.\n\n**Returns**:\n  - An attribute object that represents the `ignore_tags` sub block.\n', args=[]),
    new(
      key_prefixes=null,
      keys=null
    ):: std.prune(a={
      key_prefixes: key_prefixes,
      keys: keys,
    }),
  },
}
