local d = (import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet');
{
  '#':: d.pkg(name='aws', url='', help='The `aws` package contains functions and utilities for setting up the provider, resources, and data\nsources of the [aws Terraform provider](TODO) using Jsonnet.\n\nThis package is autogenerated from the [tf-libsonnet/libgenerator](https://github.com/tf-libsonnet/libgenerator)\nproject.\n'),
  provider: (import 'provider_aws.libsonnet'),
  data: (import 'data/main.libsonnet'),
} + (import 'resources/main.libsonnet')
