local tf = (import 'github.com/tf-libsonnet/core/main.libsonnet');
{
  new(
    access_key=null,
    allowed_account_ids=null,
    assume_role=null,
    assume_role_with_web_identity=null,
    custom_ca_bundle=null,
    default_tags=null,
    ec2_metadata_service_endpoint=null,
    ec2_metadata_service_endpoint_mode=null,
    endpoints=null,
    forbidden_account_ids=null,
    http_proxy=null,
    ignore_tags=null,
    insecure=null,
    max_retries=null,
    profile=null,
    region=null,
    s3_force_path_style=null,
    s3_use_path_style=null,
    secret_key=null,
    shared_config_files=null,
    shared_credentials_file=null,
    shared_credentials_files=null,
    skip_credentials_validation=null,
    skip_get_ec2_platforms=null,
    skip_metadata_api_check=null,
    skip_region_validation=null,
    skip_requesting_account_id=null,
    sts_region=null,
    token=null,
    use_dualstack_endpoint=null,
    use_fips_endpoint=null,
    alias=null,
    src=null,
    version=null
  ):: tf.withProvider(
    name='aws',
    alias=alias,
    src=src,
    version=version,
    attrs=self.newAttrs(
      access_key=access_key,
      allowed_account_ids=allowed_account_ids,
      assume_role=assume_role,
      assume_role_with_web_identity=assume_role_with_web_identity,
      custom_ca_bundle=custom_ca_bundle,
      default_tags=default_tags,
      ec2_metadata_service_endpoint=ec2_metadata_service_endpoint,
      ec2_metadata_service_endpoint_mode=ec2_metadata_service_endpoint_mode,
      endpoints=endpoints,
      forbidden_account_ids=forbidden_account_ids,
      http_proxy=http_proxy,
      ignore_tags=ignore_tags,
      insecure=insecure,
      max_retries=max_retries,
      profile=profile,
      region=region,
      s3_force_path_style=s3_force_path_style,
      s3_use_path_style=s3_use_path_style,
      secret_key=secret_key,
      shared_config_files=shared_config_files,
      shared_credentials_file=shared_credentials_file,
      shared_credentials_files=shared_credentials_files,
      skip_credentials_validation=skip_credentials_validation,
      skip_get_ec2_platforms=skip_get_ec2_platforms,
      skip_metadata_api_check=skip_metadata_api_check,
      skip_region_validation=skip_region_validation,
      skip_requesting_account_id=skip_requesting_account_id,
      sts_region=sts_region,
      token=token,
      use_dualstack_endpoint=use_dualstack_endpoint,
      use_fips_endpoint=use_fips_endpoint
    )
  ),
  newAttrs(
    access_key=null,
    allowed_account_ids=null,
    assume_role=null,
    assume_role_with_web_identity=null,
    custom_ca_bundle=null,
    default_tags=null,
    ec2_metadata_service_endpoint=null,
    ec2_metadata_service_endpoint_mode=null,
    endpoints=null,
    forbidden_account_ids=null,
    http_proxy=null,
    ignore_tags=null,
    insecure=null,
    max_retries=null,
    profile=null,
    region=null,
    s3_force_path_style=null,
    s3_use_path_style=null,
    secret_key=null,
    shared_config_files=null,
    shared_credentials_file=null,
    shared_credentials_files=null,
    skip_credentials_validation=null,
    skip_get_ec2_platforms=null,
    skip_metadata_api_check=null,
    skip_region_validation=null,
    skip_requesting_account_id=null,
    sts_region=null,
    token=null,
    use_dualstack_endpoint=null,
    use_fips_endpoint=null
  ):: std.prune(a={
    access_key: access_key,
    allowed_account_ids: allowed_account_ids,
    assume_role: assume_role,
    assume_role_with_web_identity: assume_role_with_web_identity,
    custom_ca_bundle: custom_ca_bundle,
    default_tags: default_tags,
    ec2_metadata_service_endpoint: ec2_metadata_service_endpoint,
    ec2_metadata_service_endpoint_mode: ec2_metadata_service_endpoint_mode,
    endpoints: endpoints,
    forbidden_account_ids: forbidden_account_ids,
    http_proxy: http_proxy,
    ignore_tags: ignore_tags,
    insecure: insecure,
    max_retries: max_retries,
    profile: profile,
    region: region,
    s3_force_path_style: s3_force_path_style,
    s3_use_path_style: s3_use_path_style,
    secret_key: secret_key,
    shared_config_files: shared_config_files,
    shared_credentials_file: shared_credentials_file,
    shared_credentials_files: shared_credentials_files,
    skip_credentials_validation: skip_credentials_validation,
    skip_get_ec2_platforms: skip_get_ec2_platforms,
    skip_metadata_api_check: skip_metadata_api_check,
    skip_region_validation: skip_region_validation,
    skip_requesting_account_id: skip_requesting_account_id,
    sts_region: sts_region,
    token: token,
    use_dualstack_endpoint: use_dualstack_endpoint,
    use_fips_endpoint: use_fips_endpoint,
  }),
  assume_role:: {
    new(
      duration=null,
      duration_seconds=null,
      external_id=null,
      policy=null,
      policy_arns=null,
      role_arn=null,
      session_name=null,
      source_identity=null,
      tags=null,
      transitive_tag_keys=null
    ):: std.prune(a={
      duration: duration,
      duration_seconds: duration_seconds,
      external_id: external_id,
      policy: policy,
      policy_arns: policy_arns,
      role_arn: role_arn,
      session_name: session_name,
      source_identity: source_identity,
      tags: tags,
      transitive_tag_keys: transitive_tag_keys,
    }),
  },
  assume_role_with_web_identity:: {
    new(
      duration=null,
      policy=null,
      policy_arns=null,
      role_arn=null,
      session_name=null,
      web_identity_token=null,
      web_identity_token_file=null
    ):: std.prune(a={
      duration: duration,
      policy: policy,
      policy_arns: policy_arns,
      role_arn: role_arn,
      session_name: session_name,
      web_identity_token: web_identity_token,
      web_identity_token_file: web_identity_token_file,
    }),
  },
  default_tags:: {
    new(
      tags=null
    ):: std.prune(a={
      tags: tags,
    }),
  },
  endpoints:: {
    new(
      accessanalyzer=null,
      account=null,
      acm=null,
      acmpca=null,
      alexaforbusiness=null,
      amg=null,
      amp=null,
      amplify=null,
      amplifybackend=null,
      amplifyuibuilder=null,
      apigateway=null,
      apigatewaymanagementapi=null,
      apigatewayv2=null,
      appautoscaling=null,
      appconfig=null,
      appconfigdata=null,
      appflow=null,
      appintegrations=null,
      appintegrationsservice=null,
      applicationautoscaling=null,
      applicationcostprofiler=null,
      applicationdiscovery=null,
      applicationdiscoveryservice=null,
      applicationinsights=null,
      appmesh=null,
      appregistry=null,
      apprunner=null,
      appstream=null,
      appsync=null,
      athena=null,
      auditmanager=null,
      augmentedairuntime=null,
      autoscaling=null,
      autoscalingplans=null,
      backup=null,
      backupgateway=null,
      batch=null,
      beanstalk=null,
      billingconductor=null,
      braket=null,
      budgets=null,
      ce=null,
      chime=null,
      chimesdkidentity=null,
      chimesdkmeetings=null,
      chimesdkmessaging=null,
      cloud9=null,
      cloudcontrol=null,
      cloudcontrolapi=null,
      clouddirectory=null,
      cloudformation=null,
      cloudfront=null,
      cloudhsm=null,
      cloudhsmv2=null,
      cloudsearch=null,
      cloudsearchdomain=null,
      cloudtrail=null,
      cloudwatch=null,
      cloudwatchevents=null,
      cloudwatchevidently=null,
      cloudwatchlog=null,
      cloudwatchlogs=null,
      cloudwatchrum=null,
      codeartifact=null,
      codebuild=null,
      codecommit=null,
      codedeploy=null,
      codeguruprofiler=null,
      codegurureviewer=null,
      codepipeline=null,
      codestar=null,
      codestarconnections=null,
      codestarnotifications=null,
      cognitoidentity=null,
      cognitoidentityprovider=null,
      cognitoidp=null,
      cognitosync=null,
      comprehend=null,
      comprehendmedical=null,
      computeoptimizer=null,
      config=null,
      configservice=null,
      connect=null,
      connectcontactlens=null,
      connectparticipant=null,
      connectwisdomservice=null,
      controltower=null,
      costandusagereportservice=null,
      costexplorer=null,
      cur=null,
      customerprofiles=null,
      databasemigration=null,
      databasemigrationservice=null,
      databrew=null,
      dataexchange=null,
      datapipeline=null,
      datasync=null,
      dax=null,
      deploy=null,
      detective=null,
      devicefarm=null,
      devopsguru=null,
      directconnect=null,
      directoryservice=null,
      discovery=null,
      dlm=null,
      dms=null,
      docdb=null,
      drs=null,
      ds=null,
      dynamodb=null,
      dynamodbstreams=null,
      ebs=null,
      ec2=null,
      ec2instanceconnect=null,
      ecr=null,
      ecrpublic=null,
      ecs=null,
      efs=null,
      eks=null,
      elasticache=null,
      elasticbeanstalk=null,
      elasticinference=null,
      elasticloadbalancing=null,
      elasticloadbalancingv2=null,
      elasticsearch=null,
      elasticsearchservice=null,
      elastictranscoder=null,
      elb=null,
      elbv2=null,
      emr=null,
      emrcontainers=null,
      emrserverless=null,
      es=null,
      eventbridge=null,
      events=null,
      evidently=null,
      finspace=null,
      finspacedata=null,
      firehose=null,
      fis=null,
      fms=null,
      forecast=null,
      forecastquery=null,
      forecastqueryservice=null,
      forecastservice=null,
      frauddetector=null,
      fsx=null,
      gamelift=null,
      glacier=null,
      globalaccelerator=null,
      glue=null,
      gluedatabrew=null,
      grafana=null,
      greengrass=null,
      greengrassv2=null,
      groundstation=null,
      guardduty=null,
      health=null,
      healthlake=null,
      honeycode=null,
      iam=null,
      identitystore=null,
      imagebuilder=null,
      inspector=null,
      inspector2=null,
      inspectorv2=null,
      iot=null,
      iot1clickdevices=null,
      iot1clickdevicesservice=null,
      iot1clickprojects=null,
      iotanalytics=null,
      iotdata=null,
      iotdataplane=null,
      iotdeviceadvisor=null,
      iotevents=null,
      ioteventsdata=null,
      iotfleethub=null,
      iotjobsdata=null,
      iotjobsdataplane=null,
      iotsecuretunneling=null,
      iotsitewise=null,
      iotthingsgraph=null,
      iottwinmaker=null,
      iotwireless=null,
      ivs=null,
      ivschat=null,
      kafka=null,
      kafkaconnect=null,
      kendra=null,
      keyspaces=null,
      kinesis=null,
      kinesisanalytics=null,
      kinesisanalyticsv2=null,
      kinesisvideo=null,
      kinesisvideoarchivedmedia=null,
      kinesisvideomedia=null,
      kinesisvideosignaling=null,
      kinesisvideosignalingchannels=null,
      kms=null,
      lakeformation=null,
      lambda=null,
      lex=null,
      lexmodelbuilding=null,
      lexmodelbuildingservice=null,
      lexmodels=null,
      lexmodelsv2=null,
      lexruntime=null,
      lexruntimeservice=null,
      lexruntimev2=null,
      lexv2models=null,
      lexv2runtime=null,
      licensemanager=null,
      lightsail=null,
      location=null,
      locationservice=null,
      logs=null,
      lookoutequipment=null,
      lookoutforvision=null,
      lookoutmetrics=null,
      lookoutvision=null,
      machinelearning=null,
      macie=null,
      macie2=null,
      managedblockchain=null,
      managedgrafana=null,
      marketplacecatalog=null,
      marketplacecommerceanalytics=null,
      marketplaceentitlement=null,
      marketplaceentitlementservice=null,
      marketplacemetering=null,
      mediaconnect=null,
      mediaconvert=null,
      medialive=null,
      mediapackage=null,
      mediapackagevod=null,
      mediastore=null,
      mediastoredata=null,
      mediatailor=null,
      memorydb=null,
      meteringmarketplace=null,
      mgh=null,
      mgn=null,
      migrationhub=null,
      migrationhubconfig=null,
      migrationhubrefactorspaces=null,
      migrationhubstrategy=null,
      migrationhubstrategyrecommendations=null,
      mobile=null,
      mq=null,
      msk=null,
      mturk=null,
      mwaa=null,
      neptune=null,
      networkfirewall=null,
      networkmanager=null,
      nimble=null,
      nimblestudio=null,
      opensearch=null,
      opensearchservice=null,
      opsworks=null,
      opsworkscm=null,
      organizations=null,
      outposts=null,
      panorama=null,
      personalize=null,
      personalizeevents=null,
      personalizeruntime=null,
      pi=null,
      pinpoint=null,
      pinpointemail=null,
      pinpointsmsvoice=null,
      pipes=null,
      polly=null,
      pricing=null,
      prometheus=null,
      prometheusservice=null,
      proton=null,
      qldb=null,
      qldbsession=null,
      quicksight=null,
      ram=null,
      rbin=null,
      rds=null,
      rdsdata=null,
      rdsdataservice=null,
      recyclebin=null,
      redshift=null,
      redshiftdata=null,
      redshiftdataapiservice=null,
      redshiftserverless=null,
      rekognition=null,
      resiliencehub=null,
      resourceexplorer2=null,
      resourcegroups=null,
      resourcegroupstagging=null,
      resourcegroupstaggingapi=null,
      robomaker=null,
      rolesanywhere=null,
      route53=null,
      route53domains=null,
      route53recoverycluster=null,
      route53recoverycontrolconfig=null,
      route53recoveryreadiness=null,
      route53resolver=null,
      rum=null,
      s3=null,
      s3api=null,
      s3control=null,
      s3outposts=null,
      sagemaker=null,
      sagemakera2iruntime=null,
      sagemakeredge=null,
      sagemakeredgemanager=null,
      sagemakerfeaturestoreruntime=null,
      sagemakerruntime=null,
      savingsplans=null,
      scheduler=null,
      schemas=null,
      sdb=null,
      secretsmanager=null,
      securityhub=null,
      serverlessapplicationrepository=null,
      serverlessapprepo=null,
      serverlessrepo=null,
      servicecatalog=null,
      servicecatalogappregistry=null,
      servicediscovery=null,
      servicequotas=null,
      ses=null,
      sesv2=null,
      sfn=null,
      shield=null,
      signer=null,
      simpledb=null,
      sms=null,
      snowball=null,
      snowdevicemanagement=null,
      sns=null,
      sqs=null,
      ssm=null,
      ssmcontacts=null,
      ssmincidents=null,
      sso=null,
      ssoadmin=null,
      ssooidc=null,
      stepfunctions=null,
      storagegateway=null,
      sts=null,
      support=null,
      swf=null,
      synthetics=null,
      textract=null,
      timestreamquery=null,
      timestreamwrite=null,
      transcribe=null,
      transcribeservice=null,
      transcribestreaming=null,
      transcribestreamingservice=null,
      transfer=null,
      translate=null,
      voiceid=null,
      waf=null,
      wafregional=null,
      wafv2=null,
      wellarchitected=null,
      wisdom=null,
      workdocs=null,
      worklink=null,
      workmail=null,
      workmailmessageflow=null,
      workspaces=null,
      workspacesweb=null,
      xray=null
    ):: std.prune(a={
      accessanalyzer: accessanalyzer,
      account: account,
      acm: acm,
      acmpca: acmpca,
      alexaforbusiness: alexaforbusiness,
      amg: amg,
      amp: amp,
      amplify: amplify,
      amplifybackend: amplifybackend,
      amplifyuibuilder: amplifyuibuilder,
      apigateway: apigateway,
      apigatewaymanagementapi: apigatewaymanagementapi,
      apigatewayv2: apigatewayv2,
      appautoscaling: appautoscaling,
      appconfig: appconfig,
      appconfigdata: appconfigdata,
      appflow: appflow,
      appintegrations: appintegrations,
      appintegrationsservice: appintegrationsservice,
      applicationautoscaling: applicationautoscaling,
      applicationcostprofiler: applicationcostprofiler,
      applicationdiscovery: applicationdiscovery,
      applicationdiscoveryservice: applicationdiscoveryservice,
      applicationinsights: applicationinsights,
      appmesh: appmesh,
      appregistry: appregistry,
      apprunner: apprunner,
      appstream: appstream,
      appsync: appsync,
      athena: athena,
      auditmanager: auditmanager,
      augmentedairuntime: augmentedairuntime,
      autoscaling: autoscaling,
      autoscalingplans: autoscalingplans,
      backup: backup,
      backupgateway: backupgateway,
      batch: batch,
      beanstalk: beanstalk,
      billingconductor: billingconductor,
      braket: braket,
      budgets: budgets,
      ce: ce,
      chime: chime,
      chimesdkidentity: chimesdkidentity,
      chimesdkmeetings: chimesdkmeetings,
      chimesdkmessaging: chimesdkmessaging,
      cloud9: cloud9,
      cloudcontrol: cloudcontrol,
      cloudcontrolapi: cloudcontrolapi,
      clouddirectory: clouddirectory,
      cloudformation: cloudformation,
      cloudfront: cloudfront,
      cloudhsm: cloudhsm,
      cloudhsmv2: cloudhsmv2,
      cloudsearch: cloudsearch,
      cloudsearchdomain: cloudsearchdomain,
      cloudtrail: cloudtrail,
      cloudwatch: cloudwatch,
      cloudwatchevents: cloudwatchevents,
      cloudwatchevidently: cloudwatchevidently,
      cloudwatchlog: cloudwatchlog,
      cloudwatchlogs: cloudwatchlogs,
      cloudwatchrum: cloudwatchrum,
      codeartifact: codeartifact,
      codebuild: codebuild,
      codecommit: codecommit,
      codedeploy: codedeploy,
      codeguruprofiler: codeguruprofiler,
      codegurureviewer: codegurureviewer,
      codepipeline: codepipeline,
      codestar: codestar,
      codestarconnections: codestarconnections,
      codestarnotifications: codestarnotifications,
      cognitoidentity: cognitoidentity,
      cognitoidentityprovider: cognitoidentityprovider,
      cognitoidp: cognitoidp,
      cognitosync: cognitosync,
      comprehend: comprehend,
      comprehendmedical: comprehendmedical,
      computeoptimizer: computeoptimizer,
      config: config,
      configservice: configservice,
      connect: connect,
      connectcontactlens: connectcontactlens,
      connectparticipant: connectparticipant,
      connectwisdomservice: connectwisdomservice,
      controltower: controltower,
      costandusagereportservice: costandusagereportservice,
      costexplorer: costexplorer,
      cur: cur,
      customerprofiles: customerprofiles,
      databasemigration: databasemigration,
      databasemigrationservice: databasemigrationservice,
      databrew: databrew,
      dataexchange: dataexchange,
      datapipeline: datapipeline,
      datasync: datasync,
      dax: dax,
      deploy: deploy,
      detective: detective,
      devicefarm: devicefarm,
      devopsguru: devopsguru,
      directconnect: directconnect,
      directoryservice: directoryservice,
      discovery: discovery,
      dlm: dlm,
      dms: dms,
      docdb: docdb,
      drs: drs,
      ds: ds,
      dynamodb: dynamodb,
      dynamodbstreams: dynamodbstreams,
      ebs: ebs,
      ec2: ec2,
      ec2instanceconnect: ec2instanceconnect,
      ecr: ecr,
      ecrpublic: ecrpublic,
      ecs: ecs,
      efs: efs,
      eks: eks,
      elasticache: elasticache,
      elasticbeanstalk: elasticbeanstalk,
      elasticinference: elasticinference,
      elasticloadbalancing: elasticloadbalancing,
      elasticloadbalancingv2: elasticloadbalancingv2,
      elasticsearch: elasticsearch,
      elasticsearchservice: elasticsearchservice,
      elastictranscoder: elastictranscoder,
      elb: elb,
      elbv2: elbv2,
      emr: emr,
      emrcontainers: emrcontainers,
      emrserverless: emrserverless,
      es: es,
      eventbridge: eventbridge,
      events: events,
      evidently: evidently,
      finspace: finspace,
      finspacedata: finspacedata,
      firehose: firehose,
      fis: fis,
      fms: fms,
      forecast: forecast,
      forecastquery: forecastquery,
      forecastqueryservice: forecastqueryservice,
      forecastservice: forecastservice,
      frauddetector: frauddetector,
      fsx: fsx,
      gamelift: gamelift,
      glacier: glacier,
      globalaccelerator: globalaccelerator,
      glue: glue,
      gluedatabrew: gluedatabrew,
      grafana: grafana,
      greengrass: greengrass,
      greengrassv2: greengrassv2,
      groundstation: groundstation,
      guardduty: guardduty,
      health: health,
      healthlake: healthlake,
      honeycode: honeycode,
      iam: iam,
      identitystore: identitystore,
      imagebuilder: imagebuilder,
      inspector: inspector,
      inspector2: inspector2,
      inspectorv2: inspectorv2,
      iot: iot,
      iot1clickdevices: iot1clickdevices,
      iot1clickdevicesservice: iot1clickdevicesservice,
      iot1clickprojects: iot1clickprojects,
      iotanalytics: iotanalytics,
      iotdata: iotdata,
      iotdataplane: iotdataplane,
      iotdeviceadvisor: iotdeviceadvisor,
      iotevents: iotevents,
      ioteventsdata: ioteventsdata,
      iotfleethub: iotfleethub,
      iotjobsdata: iotjobsdata,
      iotjobsdataplane: iotjobsdataplane,
      iotsecuretunneling: iotsecuretunneling,
      iotsitewise: iotsitewise,
      iotthingsgraph: iotthingsgraph,
      iottwinmaker: iottwinmaker,
      iotwireless: iotwireless,
      ivs: ivs,
      ivschat: ivschat,
      kafka: kafka,
      kafkaconnect: kafkaconnect,
      kendra: kendra,
      keyspaces: keyspaces,
      kinesis: kinesis,
      kinesisanalytics: kinesisanalytics,
      kinesisanalyticsv2: kinesisanalyticsv2,
      kinesisvideo: kinesisvideo,
      kinesisvideoarchivedmedia: kinesisvideoarchivedmedia,
      kinesisvideomedia: kinesisvideomedia,
      kinesisvideosignaling: kinesisvideosignaling,
      kinesisvideosignalingchannels: kinesisvideosignalingchannels,
      kms: kms,
      lakeformation: lakeformation,
      lambda: lambda,
      lex: lex,
      lexmodelbuilding: lexmodelbuilding,
      lexmodelbuildingservice: lexmodelbuildingservice,
      lexmodels: lexmodels,
      lexmodelsv2: lexmodelsv2,
      lexruntime: lexruntime,
      lexruntimeservice: lexruntimeservice,
      lexruntimev2: lexruntimev2,
      lexv2models: lexv2models,
      lexv2runtime: lexv2runtime,
      licensemanager: licensemanager,
      lightsail: lightsail,
      location: location,
      locationservice: locationservice,
      logs: logs,
      lookoutequipment: lookoutequipment,
      lookoutforvision: lookoutforvision,
      lookoutmetrics: lookoutmetrics,
      lookoutvision: lookoutvision,
      machinelearning: machinelearning,
      macie: macie,
      macie2: macie2,
      managedblockchain: managedblockchain,
      managedgrafana: managedgrafana,
      marketplacecatalog: marketplacecatalog,
      marketplacecommerceanalytics: marketplacecommerceanalytics,
      marketplaceentitlement: marketplaceentitlement,
      marketplaceentitlementservice: marketplaceentitlementservice,
      marketplacemetering: marketplacemetering,
      mediaconnect: mediaconnect,
      mediaconvert: mediaconvert,
      medialive: medialive,
      mediapackage: mediapackage,
      mediapackagevod: mediapackagevod,
      mediastore: mediastore,
      mediastoredata: mediastoredata,
      mediatailor: mediatailor,
      memorydb: memorydb,
      meteringmarketplace: meteringmarketplace,
      mgh: mgh,
      mgn: mgn,
      migrationhub: migrationhub,
      migrationhubconfig: migrationhubconfig,
      migrationhubrefactorspaces: migrationhubrefactorspaces,
      migrationhubstrategy: migrationhubstrategy,
      migrationhubstrategyrecommendations: migrationhubstrategyrecommendations,
      mobile: mobile,
      mq: mq,
      msk: msk,
      mturk: mturk,
      mwaa: mwaa,
      neptune: neptune,
      networkfirewall: networkfirewall,
      networkmanager: networkmanager,
      nimble: nimble,
      nimblestudio: nimblestudio,
      opensearch: opensearch,
      opensearchservice: opensearchservice,
      opsworks: opsworks,
      opsworkscm: opsworkscm,
      organizations: organizations,
      outposts: outposts,
      panorama: panorama,
      personalize: personalize,
      personalizeevents: personalizeevents,
      personalizeruntime: personalizeruntime,
      pi: pi,
      pinpoint: pinpoint,
      pinpointemail: pinpointemail,
      pinpointsmsvoice: pinpointsmsvoice,
      pipes: pipes,
      polly: polly,
      pricing: pricing,
      prometheus: prometheus,
      prometheusservice: prometheusservice,
      proton: proton,
      qldb: qldb,
      qldbsession: qldbsession,
      quicksight: quicksight,
      ram: ram,
      rbin: rbin,
      rds: rds,
      rdsdata: rdsdata,
      rdsdataservice: rdsdataservice,
      recyclebin: recyclebin,
      redshift: redshift,
      redshiftdata: redshiftdata,
      redshiftdataapiservice: redshiftdataapiservice,
      redshiftserverless: redshiftserverless,
      rekognition: rekognition,
      resiliencehub: resiliencehub,
      resourceexplorer2: resourceexplorer2,
      resourcegroups: resourcegroups,
      resourcegroupstagging: resourcegroupstagging,
      resourcegroupstaggingapi: resourcegroupstaggingapi,
      robomaker: robomaker,
      rolesanywhere: rolesanywhere,
      route53: route53,
      route53domains: route53domains,
      route53recoverycluster: route53recoverycluster,
      route53recoverycontrolconfig: route53recoverycontrolconfig,
      route53recoveryreadiness: route53recoveryreadiness,
      route53resolver: route53resolver,
      rum: rum,
      s3: s3,
      s3api: s3api,
      s3control: s3control,
      s3outposts: s3outposts,
      sagemaker: sagemaker,
      sagemakera2iruntime: sagemakera2iruntime,
      sagemakeredge: sagemakeredge,
      sagemakeredgemanager: sagemakeredgemanager,
      sagemakerfeaturestoreruntime: sagemakerfeaturestoreruntime,
      sagemakerruntime: sagemakerruntime,
      savingsplans: savingsplans,
      scheduler: scheduler,
      schemas: schemas,
      sdb: sdb,
      secretsmanager: secretsmanager,
      securityhub: securityhub,
      serverlessapplicationrepository: serverlessapplicationrepository,
      serverlessapprepo: serverlessapprepo,
      serverlessrepo: serverlessrepo,
      servicecatalog: servicecatalog,
      servicecatalogappregistry: servicecatalogappregistry,
      servicediscovery: servicediscovery,
      servicequotas: servicequotas,
      ses: ses,
      sesv2: sesv2,
      sfn: sfn,
      shield: shield,
      signer: signer,
      simpledb: simpledb,
      sms: sms,
      snowball: snowball,
      snowdevicemanagement: snowdevicemanagement,
      sns: sns,
      sqs: sqs,
      ssm: ssm,
      ssmcontacts: ssmcontacts,
      ssmincidents: ssmincidents,
      sso: sso,
      ssoadmin: ssoadmin,
      ssooidc: ssooidc,
      stepfunctions: stepfunctions,
      storagegateway: storagegateway,
      sts: sts,
      support: support,
      swf: swf,
      synthetics: synthetics,
      textract: textract,
      timestreamquery: timestreamquery,
      timestreamwrite: timestreamwrite,
      transcribe: transcribe,
      transcribeservice: transcribeservice,
      transcribestreaming: transcribestreaming,
      transcribestreamingservice: transcribestreamingservice,
      transfer: transfer,
      translate: translate,
      voiceid: voiceid,
      waf: waf,
      wafregional: wafregional,
      wafv2: wafv2,
      wellarchitected: wellarchitected,
      wisdom: wisdom,
      workdocs: workdocs,
      worklink: worklink,
      workmail: workmail,
      workmailmessageflow: workmailmessageflow,
      workspaces: workspaces,
      workspacesweb: workspacesweb,
      xray: xray,
    }),
  },
  ignore_tags:: {
    new(
      key_prefixes=null,
      keys=null
    ):: std.prune(a={
      key_prefixes: key_prefixes,
      keys: keys,
    }),
  },
}
